apiVersion: skaffold/v1beta13
kind: Config
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
    - image: moizhsu/gokitconsulk8s-addsvc
      custom:
        buildCommand: "make dev_docker_addsvc"
        dependencies:
          paths:
            - cmd/addsvc/main.go
            - pkg/addsvc
    - image: moizhsu/gokitconsulk8s-foosvc
      custom:
        buildCommand: "make dev_docker_foosvc"
        dependencies:
          paths:
            - cmd/foosvc/main.go
            - pkg/foosvc
    - image: moizhsu/gokitconsulk8s-router
      custom:
        buildCommand: "make dev_docker_router"
        dependencies:
          paths:
            - cmd/router/main.go
            - pkg/router
    - image: cage1016/gokitconsulk8s-website
      context: deployments/k8s/website
      docker:
        dockerfile: DockerFile
    - image: moizhsu/gokitconsulk8s-producersvc
      custom:
        buildCommand: "make dev_docker_producersvc"
        dependencies:
          paths:
            - cmd/producersvc/main.go
            - pkg/producersvc
deploy:
  kubectl:
    manifests:
      - ./deployments/k8s/*.yaml
