apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: producersvc
  creationTimestamp: null
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  name: producersvc
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: producersvc
  template:
    metadata:
      labels:
        io.kompose.service: producersvc
      creationTimestamp: null
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "producersvc"
        "consul.hashicorp.com/connect-service-port": "6021"
        "consul.hashicorp.com/connect-service-protocol": "grpc"
        "consul.hashicorp.com/connect-service-upstreams": "zipkin:9411"
    spec:
      containers:
        - env:
            - name: QS_PRODUCERSVC_GRPC_PORT
              value: "6021"
            - name: QS_PRODUCERSVC_HTTP_PORT
              value: "6020"
            - name: QS_PRODUCERSVC_LOG_LEVEL
              value: info
            - name: QS_ZIPKIN_V2_URL
              value: http://localhost:9411/api/v2/spans
          image: moizhsu/gokitconsulk8s-producersvc
          name: producersvc
          resources: {}
      restartPolicy: Always
status: {}
